Doxygen Configuration File
ros-industrial/stomp_ros pull request #18
Opened 2020-04-28 15:32 UTC by marip8

This PR adds the doxygen configuration file from the [industrial_moveit](https://github.com/ros-industrial/industrial_moveit) project per #8 so that documentation for STOMP can be generated

2020-04-28 16:17 UTC, gavanderhoorn requested changes
As this was a direct copy a few things need updating I believe.

2020-04-28 16:17 UTC, gavanderhoorn commented on doxygen.config
> +PROJECT_NAME           = "Industrial Moveit"
Should this be changed to reflect the new location?

2020-04-28 16:17 UTC, gavanderhoorn commented on doxygen.config
> +INPUT                  = constrained_ik stomp_core stomp_moveit stomp_plugins
```suggestion
INPUT                  = stomp_core stomp_moveit stomp_plugins
```

2020-04-28 18:50 UTC, jrgnicho approved these changes

2020-04-28 18:52 UTC, merged

2020-05-05 14:57 UTC, jrgnicho commented
fixes #8